### ISSUE TITLE
the package.json may wrong

### ISSUE THREAD

**Issue by laureler** [silexlabs/Prodotype#2]
"build:editor": "browserify src/Prodotype.js -o pub/prodotype.js -t [ babelify ] && node bin/appendejslib",
and i think it lost  `node`;
npm install was wrong the same reason, and i saw it  at https://github.com/silexlabs/Silex/issues/574 . maybe you forget it. my english is poor, whatever im nervous:D

**Comment by lexoyo** [comment]
hi @laureler 

> my english is poor, whatever im nervous:D

haha, don't worry english is always poor!! (just joking)

> and i think it lost node;

you think we should remove "node" ?

**Comment by laureler** [comment]
nope,
is this right? "build:editor": "browserify src/Prodotype.js -o pub/prodotype.js -t [ babelify ] && node bin/appendejslib"
or with out node after &&
"build:editor": "browserify src/Prodotype.js -o pub/prodotype.js -t [ babelify ] && bin/appendejslib".
i d like to know

**Comment by lexoyo** [comment]
Oh ok, this was a question then :)
There is a "shebang" here https://github.com/silexlabs/Prodotype/blob/master/bin/appendejslib#L1
... so it should not be necessary. But just to be sure and explicit I like to keep it

**Comment by lexoyo** [comment]
Anything else?
I close the issue but feel free to reopen it :)
